import type { HistoryFeature } from 'makeHistoryData/features';
import featureLookupJson from 'public/history/featureLookup.json';
import featureIdsJson from 'public/history/featureIds.json';
import boundsJson from 'public/history/bounds.json';

// Generated by `pnpm preprocess` from makeHistoryData/features.ts; the JSON
// literal types are widened here once instead of at every import.
export const featureLookup = featureLookupJson as unknown as Record<
  string,
  HistoryFeature
>;

export const featureIds = featureIdsJson as number[];

export const historyBounds = boundsJson as [
  number,
  number,
  number,
  number,
];
