import type { Map as MapboxMap } from 'mapbox-gl';
import type { HistoryFeature } from 'makeHistoryData/features';
import featureLookupJson from 'public/history/featureLookup.json';
import featureIdsJson from 'public/history/featureIds.json';
import boundsJson from 'public/history/bounds.json';
import mapLayersJson from 'public/history/mapLayers.json';
import mapLayerIdsJson from 'public/history/mapLayerIds.json';

// Generated by `pnpm preprocess` from makeHistoryData/features.ts; the JSON
// literal types are widened here once instead of at every import.

// Keyed by feature id; an unknown id yields undefined.
export const featureLookup = featureLookupJson as unknown as Partial<
  Record<number, HistoryFeature>
>;

// Feature ids in chronological order.
export const featureIds = featureIdsJson as number[];

export const historyBounds = boundsJson as [
  number,
  number,
  number,
  number,
];

// The layer type accepted by Map#addLayer, which allows inline sources.
export type MapLayer = Parameters<MapboxMap['addLayer']>[0];

export const mapLayers = mapLayersJson as MapLayer[];

export const mapLayerIds: string[] = mapLayerIdsJson;
